version: '3.7'

services:
  django_movie:
    build: ./
    container_name: django_movie
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app/
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:12.0-alpine
    container_name: movie_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    container_name: movie_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - django_movie

volumes:
  pg_data:
